/*
ABOUT

DATE: 2021-09-14

URL: https://programmers.co.kr/learn/courses/30/lessons/59041

COMMENT:
NAME의 개수가 두 번 이상인 경우를 센다.
*/

SELECT NAME, COUNT(ANIMAL_INS.NAME)
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(ANIMAL_INS.NAME) > 1
ORDER BY NAME;