/*
ABOUT

DATE: 2021-09-13

URL: https://programmers.co.kr/learn/courses/30/lessons/59042

COMMENT:
ANIMAL_OUTS에는 있는데 ANIMAL_INS에는 없는 동물을 찾으면 되므로
RIHGT JOIN을 한 후 ANIMAL_INS의 ANIMAL_ID가 NULL인 경우를 찾는다.
*/

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_INS
RIGHT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL;