/*
ABOUT

DATE: 2021-10-15

URL: https://programmers.co.kr/learn/courses/30/lessons/59043

COMMENT:
ANIMAL_OUTS 테이블의 ANIMAL_ID가 ANIMAL_INS의 ANIMAL_ID의 외래 키이므로 JOIN을 이용한다.
*/

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME;