/*
ABOUT

DATE: 2021-10-15

URL: https://programmers.co.kr/learn/courses/30/lessons/59411

COMMENT:
입양을 간 동물 중이므로 RIGHT JOIN을 한다.
보호기간은 ANIMAL_OUTS 테이블의 DATETIME에서 ANIMAL_INS 테이블의 DATETIME을 뺀 값이다.
*/

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
RIGHT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY ANIMAL_OUTS.DATETIME - ANIMAL_INS.DATETIME DESC
LIMIT 2;