/*
ABOUT

DATE: 2021-09-13

URL: https://programmers.co.kr/learn/courses/30/lessons/59045

COMMENT:
INNER JOIN으로 합친 후 LIKE를 이용해 Intact를 가졌는지 비교한다.
*/

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.SEX_UPON_INTAKE LIKE 'Intact%'
AND ANIMAL_OUTS.SEX_UPON_OUTCOME NOT LIKE 'Intact%';